<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="294" started-at="2020-06-10T05:45:09Z" finished-at="2020-06-10T05:45:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="294" started-at="2020-06-10T05:45:09Z" finished-at="2020-06-10T05:45:09Z">
      <class name="Listener.ListnerTest">
        <test-method status="FAIL" signature="tc_02()[pri:0, instance:Listener.ListnerTest@6574b225]" name="tc_02" duration-ms="76" started-at="2020-06-10T11:15:09Z" finished-at="2020-06-10T11:15:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at Listener.ListnerTest.tc_02(ListnerTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_02 -->
        <test-method status="PASS" signature="tc_01()[pri:0, instance:Listener.ListnerTest@6574b225]" name="tc_01" duration-ms="4" started-at="2020-06-10T11:15:09Z" finished-at="2020-06-10T11:15:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_01 -->
        <test-method status="SKIP" signature="tc_03()[pri:0, instance:Listener.ListnerTest@6574b225]" name="tc_03" duration-ms="82" started-at="2020-06-10T11:15:09Z" depends-on-methods="Listener.ListnerTest.tc_02" finished-at="2020-06-10T11:15:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_03 -->
      </class> <!-- Listener.ListnerTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
